NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN

.github/validation.yml

Moving to a feature branch of main project

Merge of validation performed on a fork

---

examples/UKCore-Condition-Extension-CodingSCTDescId-Example.xml
structuredefinitions/Extension-UKCore-CareSettingType.xml

Passed workflow testing. 
Merge in with testing branch

Constraint on CareSetting extension using extension instead of element

---

valuesets/ValueSet-UKCore-MedicationCode.xml

Merge change into testing branch for testing release

Fix for issue https://simplifier.net/hl7fhirukcorer4/~issues/1851

---

examples/Patient-Extension-BirthTime-Example.xml
examples/UKCore-Bundle-AllergyList-Example.xml
examples/UKCore-Condition-Extension-CodingSCTDescId-Example.xml
examples/UKCore-Patient-Extension-AddressKey-Example.xml
examples/UKCore-Patient-Extension-OtherContactSystem-Example.xml
structuredefinitions/Extension-UKCore-CareSettingType.xml

Examples corrections. Reported by FHIR Validation

---

examples/UKCore-Medication-TimoptolEyeDrops-Example.xml

https://simplifier.net/hl7fhirukcorer4/~issues/1873

Correction of form

---

examples/UKCore-Medication-TimoptolEyeDrops-Example.xml

Correct Eye Drops code

---

valuesets/ValueSet-UKCore-CareSettingType.xml

https://simplifier.net/hl7fhirukcorer4/~issues/1870

Changed ValueSet to a contraint memberOf

---

examples/UKCore-MedicationDispense-EyeDrops-Example.xml

https://simplifier.net/hl7fhirukcorer4/~issues/1874

Changed to occular

---

examples/UKCore-MedicationStatement-Amoxicillin-Example.xml

Fixed issue with otalgia being removed from the valueset, this has been replaced by the concept above 3013354004 "pain in ear"

fixed oltalgia error

---

examples/UKCore-MedicationStatement-Amoxicillin-Example.xml

As per ballot sheet, updated MedicationStatement amoxicillin example to have a uuid identifier, and swapped effectiveDateTime to be an effectivePeriod

added identifier and switched effectiveDateTime to effectivePeriod

---

codesystems/CodeSystem-UKCore-EthnicCategoryScotland.xml

Added the source of Scotland ethnic category to the description, with & in url replaced with & (as per Ryans Marital Status for Scotland), updated date to signify its been changed post ballot

Added url for source of data, and handled &

---

structuredefinitions/UKCore-MedicationStatement.xml

Add UKCore DiagnosticReport to reasonReference to bring back in line with base fhir spec

Add UKCore DiagnosticReport to reasonReference

---

structuredefinitions/UKCore-MedicationRequest.xml

Updated version and date

---

examples/UKCore-Condition-Extension-CodingSCTDescId-Example.xml
structuredefinitions/Extension-UKCore-CodingSCTDescDisplay.xml

Noticed Display was missed from url+value. Also, uri linked to nhs. These are fixed.

Fix Extension-SCTDescDisplay

---

valuesets/ValueSet-UKCore-PracticeSettingCode.xml

valueset PracticeSettingCode fix

---

examples/UKCore-Condition-Extension-CodingSCTDescId-Example.xml
examples/UKCore-Medication-COVID-Vaccine-Example.xml
examples/UKCore-Medication-TimololVTM-Example.xml
examples/UKCore-Medication-TimoptolEyeDrops-Example.xml
structuredefinitions/Extension-UKCore-CodingSCTDescDisplay.xml

removed form from existing example as this should only be used with VTM. Added new example to show VTM+form

Fix/ballot 1.0.0 issue 121

---

valuesets/ValueSet-UKCore-AllergyCode.xml
valuesets/ValueSet-UKCore-AllergySubstance.xml
valuesets/ValueSet-UKCore-VaccineCode.xml

Fix allergy/vaccine value set wording buy adding #13; linebreaks, and missing CT to SNOMED

Fix allergy/vaccine value set wording

---

examples/UKCore-PractitionerRole-Sn-Organization-Code-Example.xml

<system value="https://fhir.nhs.uk/Id/sds-role-profile-id" />
<value value="100334993514" />
</identifier>

Changed <identifier>

---

CapabilityStatement/CapabilityStatement-UKCore.xml
examples/UKCore-Bundle-AllergyList-Example.xml
examples/UKCore-Questionnaire-InpatientSurvey-Example.xml

updated capability statement ready for UKCore STU2 IG

updated with 0.5.0 profiles

---

structuredefinitions/Extension-UKCore-DeliveryChannel.xml
structuredefinitions/Extension-UKCore-RelatedClinicalContent.xml

two extensions are missing the following code:
`<publisher value="HL7 UK"/>`
Add to both to be inline with all other files

added publisher value

---

CapabilityStatement/CapabilityStatement-UKCore.xml

CapabilityStatement is out of sync with main due to merge issues. This should sync develop back to where it should be

set capability statement the same as main

---

CapabilityStatement/CapabilityStatement-UKCore.xml

Put the derived profile VitalSigns-Observation into the capability statement

add vitalsigns to capability statement

---

codesystems/CodeSystem-UKCore-MedicationAdministrationCategory.xml
structuredefinitions/UKCore-MedicationAdministration.xml
valuesets/ValueSet-UKCore-MedicationAdministrationCategory.xml

As per MedAdmin document, change category to a ukcore valueset with a ukcore codesystem containing discharge, and the existing base codesystem

Digimeds med admin value set and code system

---

structuredefinitions/UKCore-Appointment.xml
structuredefinitions/UKCore-HealthcareService.xml
structuredefinitions/UKCore-Schedule.xml
structuredefinitions/UKCore-Slot.xml

as per standup call discussion, set Appointment.specialty and HealthcareService.specialty to match the valueset binding used on PractitionerRole.specialty

update appointment/healthcare specialty to match practitionerrole

---

valuesets/ValueSet-UKCore-AllergyManifestation.xml

stu2 version of https://nhsd-jira.digital.nhs.uk/browse/IOPS-976 to bring in line with the 1.0.0 PR

matching change from v.1.0.0 hotfixes, applied to stu2

---

structuredefinitions/UKCore-Medication.xml
structuredefinitions/UKCore-MedicationAdministration.xml
structuredefinitions/UKCore-MedicationDispense.xml
structuredefinitions/UKCore-MedicationRequest.xml
structuredefinitions/UKCore-MedicationStatement.xml

changed remaining 4 bindings to UKCore-MedicaitonCode from extensible to preferred in 1.0.0

changed binding strength as agreed

---

examples/UKCore-Condition-Sn-Extension-CodingSCT-MoleOfSkin-Example.xml

mole of skin example, fix CodingSCTDescDisplay URL
theory is this will fix the rendering of stu1 examples when pushed into main

fix single nhs url to correct hl7 uk url

---

valuesets/ValueSet-UKCore-MedicationStatementCategory.xml

as per ticket and discussion, base codesystem was being filtered via include to only have 3 out of the 4 codes - include codes for both codesystems removed, and fresh expansion done

remove base codesystem filter, fresh expansion

---

valuesets/ValueSet-UKCore-MedicationCode.xml

As discussed and agreed, add the SNOMED CT concept for trial meds into UKCore-MedicationCode

added trial drug snomed concept

---

structuredefinitions/UKCore-EpisodeOfCare.xml

Description copied from IG. Not sure if the markdown will be rendered correctly in FQL

changed profile purpose to include relationship to encounter

---

structuredefinitions/UKCore-FamilyMemberHistory.xml

Adding SD for FamilyMemberHistory to UKCore. I have maintained the status as a draft.

Adding New profile to UKCore

---

structuredefinitions/UKCore-EpisodeOfCare.xml

changed header to h4
fixed list markdown

fixed markdown in EpisodeOfCare

---

structuredefinitions/UKCore-EpisodeOfCare.xml

trying to fix merge issues.
This one is: 
branch off main
merge from develop
fix merge issues
merge into main

Fix merge issues

---

structuredefinitions/UKCore-FamilyMemberHistory.xml

Update of target profile for Identifier.assigner and note.author to their respective UKCore profiles.

Update Target profiles for Identifier and Note

---

codesystems/CodeSystem-UKCore-MedicationRequestCategory.xml
valuesets/ValueSet-UKCore-MedicationRequestCategory.xml

Added Primary Care code, removed valueset filters, fresh expansion

---

valuesets/ValueSet-UKCore-MessageEvent.xml

Also updated contact as per 1.0.0 changes that need doing
Date/Version was already set to agreed 1.1.0 values

Expansion of NHS codesystems for MessageEvent

---

examples/UKCore-RelatedPerson-JoySmith-Example.xml
structuredefinitions/Extension-UKCore-ContactRank.xml
structuredefinitions/UKCore-RelatedPerson.xml

Remove context and wording from extension,
Remove extension from profile
Remove extension from example

Remove ContactRank extension from Relatedperson (1.1.0 / stu2)

---

codesystems/CodeSystem-UKCore-MedicationAdministrationCategory.xml
structuredefinitions/UKCore-Observation-VitalSigns.xml
valuesets/ValueSet-UKCore-MedicationAdministrationCategory.xml
valuesets/ValueSet-UKCore-ObservationVitalSignsType.xml
valuesets/ValueSet-UKCore-ObservationVitalSignsValue.xml

MedAdminCategory and ObservationVitalSigns were changed in stu2 post stu1 release being tagged, and as such were not in the emails changed in the release/hotfix that were merged into develop/main

fix for ukcore email on stu2 files

---

codesystems/CodeSystem-UKCore-MedicationAdministrationCategory.xml
structuredefinitions/UKCore-Observation-VitalSigns.xml
valuesets/ValueSet-UKCore-MedicationAdministrationCategory.xml
valuesets/ValueSet-UKCore-MedicationStatementCategory.xml
valuesets/ValueSet-UKCore-ObservationVitalSignsType.xml
valuesets/ValueSet-UKCore-ObservationVitalSignsValue.xml

Merge develop into main to get email changes

Merge develop into main to get email changes

---

.gitignore
structuredefinitions/Extension-UKCore-AssociatedEncounter.StructureDefinition.xml
structuredefinitions/Extension-UKCore-Recorder.StructureDefinition.xml

Uplift of FamilyMemberHistory Extensions from STU3 to R4

Uplift of FamilyMemberHistory Extensions from STU3 to R4

---

structuredefinitions/UKCore-ImagingStudy.xml

New UKCore-ImagingStudy profile, with ukcore references to equivalent resources, and identifer.assigner mapped to UKCore-Organization
No ValueSets yet - would like to get this into develop and then into main so it can be rendered and then tweaked

Initial profile creation

---

structuredefinitions/UKCore-Specimen.xml

Swapped references to UKCore for device/servicerequest

Initial UKCore-specimen profile tweaks

---

structuredefinitions/UKCore-ImagingStudy.xml

Because I am an idiot and put the ID in the Name tag, this pr removes the - to bring it in line with the other profiles

fix name tag, removing -

---

examples/UKCore-ImagingStudy-CTChestScan-Example.xml

CT Chest Scan example for ImagingStudy, base off R5 imaging study example, and R4'ified and UK'ified

UKCore Imaging Study example

---

structuredefinitions/UKCore-Encounter.xml
structuredefinitions/UKCore-MedicationDispense.xml

UKCore-Encounter still referencing Appointment
UKCore-MedicationDispense still referencing EpisodeOfCare

Fix missing uk core references in active profiles

---

examples/UKCore-FamilyMemberHistory-FatherDiabetes.xml

FMH profile was lacking an example, this gives one for a father, with diabetes

Initial FamilyMemberHistory example

---

structuredefinitions/UKCore-Specimen.xml

Change .type Snomed CT slice binding strength to Preferred in line with new design approach

Change .type slice binding strength to Preferred

---

structuredefinitions/UKCore-Observation.xml

3 snomed ct slices on Observation, change strength to preferred in line with new design approach

Set SNOMEDCT valuesets to preferred inline with design approach

---

examples/UKCore-Medication-TimololVTM-Example.xml
examples/UKCore-MedicationRequest-EyeDrops-Example.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1091
Updated Timolol VTM to latest dm+d id
Removed from example:
Priority (IG says not to use)
Recorder (IG says only include if different)
Updated:
dosage text
frequency - this one could be argued as right either way
courseOfTherpay - from repeating to acute (single course)
Added:
route (subretinal), inline with MedAdmin example

Fix Simplifier Issue - MedicationRequest example

---

structuredefinitions/Extension-UKCore-AdmissionMethod.xml

As per title, fix glaring spelling mistake the checker picked up

Fix spelling mistake found by checker

---

examples/UKCore-Medication-Extension-MedicationTradeFamily-Example.xml
valuesets/ValueSet-UKCore-ImmunizationExplanationReason.xml

Added 2 concepts as discussed on simplifier issues
Also a fix on trade fmaily example as dm+d have changed a description

Added 2 immunization reason concepts

---

examples/UKCore-PractitionerRole-GeneralPractitioner-Example.xml
examples/UKCore-Questionnaire-InpatientSurvey-Example.xml
examples/UKCore-QuestionnaireResponse-InpatientSurvey-Example.xml
structuredefinitions/Extension-UKCore-DischargeMethod.xml

Fixed minor spelling mistakes for STU2. Version number for extension kept as is due to only minor change

fix spelling mistakes

---

examples/UKCore-Communication-FirstMMRVaccination-Example.xml
examples/UKCore-Consent-ForInformationAccess-Example.xml
examples/UKCore-DiagnosticReport-DiagnosticStudiesReport-Example.xml
examples/UKCore-Observation-WhiteCellCount-Example.xml
examples/UKCore-PractitionerRole-GeneralPractitioner-Example.xml
examples/UKCore-Questionnaire-InpatientSurvey-Example.xml
examples/UKCore-QuestionnaireResponse-InpatientSurvey-Example.xml
structuredefinitions/Extension-UKCore-DischargeMethod.xml

Fixed minor spelling mistakes. Version number for extension kept as is due to only minor change

fixed spelling mistakes

---

examples/UKCore-MedicationRequest-EyeDrops-Example.xml

Tweaked as per request from RG, email from Emma Melhuish confirming the SNOMED CT codes to use

Tweaks from RG

---

structuredefinitions/UKCore-DiagnosticReport.xml
valuesets/ValueSet-UKCore-ReportCode.xml
valuesets/ValueSet-UKCore-ReportCodeSnCT.xml

as per https://nhsd-jira.digital.nhs.uk/browse/IOPS-1274

removed SnCT from valueset name. Aligned valueset to standards

---

structuredefinitions/Extension-UKCore-AdditionalContact.xml
structuredefinitions/UKCore-ServiceRequest.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1315
New extension on ServiceRequest, referencing org/practition/practitionerrole

New extension on ServiceRequest for AdditionalContact

---

examples/UKCore-ServiceRequest-Extension-PriorityReason-Example.xml
structuredefinitions/Extension-UKCore-PriorityReason.xml
structuredefinitions/UKCore-ServiceRequest.xml

Fix for missing extension slice, constrint to element, and example

Sprint6 - service req priority extension fixes

---

examples/UKCore-Device-SoftwareAsAMedicalDevice-Example.xml
examples/UKCore-DiagnosticReport-DeviceReference-Example.xml
structuredefinitions/Extension-UKCore-DeviceReference.xml
structuredefinitions/UKCore-DiagnosticReport.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1283
https://simplifier.net/hl7fhirukcorer4/~issues/2527
New extension to handle Device on performer and resultsInterpreter on DiagnosticReport, plus examples for it

Sprint6 - diagnostic report device reference extension

---

structuredefinitions/UKCore-MedicationDispense.xml
structuredefinitions/UKCore-MedicationRequest.xml
structuredefinitions/UKCore-MedicationStatement.xml
valuesets/ValueSet-UKCore-MedicationPrecondition.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1049
As discussed, retired valuset as changing it would match the base
Reverted the binding on asNeeded[x] on MedDispense, MedRequest, MedStatement
Fixed missed extensible to preferred binding strength swap on SNOMED CT valusets
Reverted MedStatement asNeeded[x] comment to base
Note: additional min=0 added by forge

Retire valueset, and rebind to base, and fix missed strength

---

structuredefinitions/UKCore-Condition.xml
structuredefinitions/UKCore-DiagnosticReport.xml
structuredefinitions/UKCore-Observation.xml
structuredefinitions/UKCore-Procedure.xml
structuredefinitions/UKCore-ServiceRequest.xml
valuesets/ValueSet-UKCore-FindingCode.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1369
UKCore-BodySite
UKCore-FindingCode - retired

Remove bindings where it matches base

---

structuredefinitions/UKCore-Condition.xml
structuredefinitions/UKCore-Procedure.xml
structuredefinitions/UKCore-ServiceRequest.xml

https://nhsd-jira.digital.nhs.uk/browse/IOPS-1369
UKCore-BodySite where it matches base in STU2

Stu2 fixes to removed bodysite binding where it matches base

---

structuredefinitions/UKCore-Observation-Lab.xml

Readded cardinality change that disappeared after latest merges

changed value[x] cardinality to 1..1

---

examples/UKCore-Encounter-Extension-AdmissionMethod-Example.xml
examples/UKCore-Encounter-InpatientEncounter-Example.xml
structuredefinitions/Extension-UKCore-AdmissionMethod.xml
structuredefinitions/UKCore-Encounter.xml

Ballot 2, STU3 branch, Move AdmissionMethod extension to Enocunter.hospitalization

Move AdmissionMethod extension to hospitalization

---

examples/UKCore-Encounter-Extension-AdmissionMethod-Example.xml
examples/UKCore-Encounter-InpatientEncounter-Example.xml
structuredefinitions/Extension-UKCore-AdmissionMethod.xml
structuredefinitions/UKCore-Encounter.xml

Ballot 2 request, stu2 branch, move admissionMethod extension to hospitalization
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1399

Ballot2, stu2, move admissionMethod extension

---

codesystems/CodeSystem-UKCore-FundingCategory.xml
codesystems/CodeSystem-UKCore-NHSNumberUnavailableReason.xml
examples/UKCore-Patient-Extension-NHSNumberUnavailableReason-Example.xml
examples/UKCore-ServiceRequest-Extension-Coverage-Example.xml

As per Omar email, Devolved Nation code for funding cateogry and nhs number unavailable reason

Additional devolved nation code for funding/nhs unavailable

---

structuredefinitions/Extension-UKCore-AdditionalContact.xml
structuredefinitions/Extension-UKCore-AssociatedEncounter.xml
structuredefinitions/Extension-UKCore-Coverage.xml
structuredefinitions/Extension-UKCore-DeviceReference.xml
structuredefinitions/Extension-UKCore-NHSNumberUnavailableReason.xml
structuredefinitions/Extension-UKCore-PriorityReason.xml
structuredefinitions/Extension-UKCore-SourceOfServiceRequest.xml

not sure if the purpose should start with "This initially is a use case..." to emphasise that others can use it, or "The original use case is..."

added use case to descriptions

---

codesystems/CodeSystem-UKCore-EthnicCategoryScotland.xml
codesystems/CodeSystem-UKCore-PersonMaritalStatusScotland.xml
codesystems/CodeSystem-UKCore-PracticeSettingCodeEngland.xml
codesystems/CodeSystem-UKCore-PracticeSettingCodeScotland.xml
codesystems/CodeSystem-UKCore-PracticeSettingCodeWales.xml

Retired CodeSystems that should have been retired after ballot 1.

retired CodeSystems that are no longer needed after ballot 1

---

structuredefinitions/UKCore-FamilyMemberHistory.xml
structuredefinitions/UKCore-Specimen.xml

From example to preferred (for SNOMED based), or extensible for others in line with Design Approach

Increased binding strength on base bindings for Genomics

---

valuesets/ValueSet-UKCore-SpecimenType.xml

added changes as per IOPS-1295
123037004 | Body structure (body structure)
123038009 | Specimen (specimen)
removed 49755003 | Morphologically abnormal structure as part of Body structure

added new CodSystems, removed one that was part of new larger codesystem

---

structuredefinitions/Extension-UKCore-SampleState.xml

fixed the only value[x] that was not 1..1

changed value cardinality

---

valuesets/ValueSet-UKCore-NHSNumberUnavailableReason.xml

changed expansion total

---

examples/UKCore-MessageHeader-Extension-ResponseRequest-Example.xml
examples/UKCore-Organization-Extension-Period-Example.xml
examples/UKCore-Patient-Extension-BirthPlace-Example.xml
examples/UKCore-Patient-Extension-BirthTime-Example.xml
examples/UKCore-Patient-Extension-CadavericDonor-Example.xml
examples/UKCore-Patient-Extension-InterpreterRequired-Example.xml
examples/UKCore-Specimen-Extension-SampleCategory-Example.xml
examples/UKCore-Specimen-Extension-SpecialHandling-Example.xml

Add UKCore- to filename and id of base defined extension examples, fix SampleCategory example (filename, id, extension url, codesystem url, value)

Fix extension filenames

---

structuredefinitions/UKCore-DiagnosticReport-Lab.xml
structuredefinitions/UKCore-Observation-Lab.xml

STU3 - Swapped SHALL to SHOULD in the human descriptions of constraints with warning severity

STU3 - Swapped SHALL to SHOULD in warning human descriptions

---

structuredefinitions/UKCore-DiagnosticReport-Lab.xml
structuredefinitions/UKCore-Observation-Lab.xml

STU2 - Swapped SHALL to SHOULD in the human descriptions of constraints with warning severity

Swapped SHALL to SHOULD in warning human descriptions

---

CapabilityStatement/CapabilityStatement-UKCore.xml
structuredefinitions/UKCore-RequestGroup-Medication.xml

Draft profile of UKCore-RequestGroup for medication usage

Forcing just RequestGroup med profile in

---

.github/workflows/NamingSystemChecker.yml

part of https://github.com/NHSDigital/IOPS-FHIR-Test-Scripts/tree/main/NamingSystemChecker

added namingsystemchecker to actions

---

codesystems/CodeSystem-UKCore-RecordStandardHeadings.xml
valuesets/ValueSet-UKCore-CompositionSectionCode.xml

Add missing PRSB header from :https://prsb2.vercel.app/page/community-pharmacy-standardv3
and https://theprsb.org/wp-content/uploads/2023/06/Community-Pharmacy-General-Implementation-Guidance-V3.01.pdf
for GP Connect Update Record usage of UK Core Record Standard Headings
NOTE: web and pdf do not fully align, both between themselves, and existing codes, such as Allergies and adverse reaction, or Clinical Summary/Clinical Narrative
NOTE: validaiton run fails with usual 29 comments in xml issue in hapi, and 1 new medicaton example where Ciprofloxacin description has changed thats a problem for future Adam to deal with

Urgent Change - Add PRSB headers for Update Record IG

---

.github/workflows/QualityControlChecker.yml
README.md

Changed name per Martin's request

renamed Checker and updated README

---

.github/workflows/QualityControlChecker.yml
structuredefinitions/Extension-UKCore-CollectionCollector.xml
structuredefinitions/Extension-UKCore-SampleCategory.xml
structuredefinitions/UKCore-DiagnosticReport-Lab.xml
structuredefinitions/UKCore-DiagnosticReport.xml
structuredefinitions/UKCore-Observation-Lab.xml
structuredefinitions/UKCore-Observation-LabGroup.xml
structuredefinitions/UKCore-ServiceRequest-Lab.xml

Reverted back to original for UKCore-DiagnosticReport.xml as no changes needed, but due to using linux v windows it's seeing a difference at the end

added copyright

---

structuredefinitions/UKCore-Observation-VitalSigns-BloodPressure.xml
structuredefinitions/UKCore-Observation-VitalSigns-BodyHeight.xml
structuredefinitions/UKCore-Observation-VitalSigns-BodyWeight.xml
structuredefinitions/UKCore-Observation-VitalSigns-HeadCircumference.xml
structuredefinitions/UKCore-Observation-VitalSigns-RespirationRate.xml

Add missing 9279-1 to RespirationRate
Remove hard coded loinc slice displays

Add missing loinc code, remove hard coded loinc display

---

structuredefinitions/UKCore-Observation-VitalSigns-BloodPressure.xml
structuredefinitions/UKCore-Observation-VitalSigns-BodyHeight.xml
structuredefinitions/UKCore-Observation-VitalSigns-BodyWeight.xml
structuredefinitions/UKCore-Observation-VitalSigns-HeadCircumference.xml
structuredefinitions/UKCore-Observation-VitalSigns-RespirationRate.xml

Dev into Main

---

codesystems/CodeSystem-UKCore-DateTimeType.xml
codesystems/CodeSystem-UKCore-PeriodType.xml
structuredefinitions/Extension-UKCore-TypedPeriod.xml
valuesets/ValueSet-UKCore-DateTimeType.xml
valuesets/ValueSet-UKCore-PeriodType.xml

IOPS-2124 New ODS extension with associated codesystem and valueset
+ change to existing extension, and its associated codesystem and valueset

ODS changes for time/period extensions

---

CapabilityStatement/CapabilityStatement-UKCore.xml
codesystems/CodeSystem-UKCore-DateTimeType.xml
structuredefinitions/Extension-UKCore-TypedPeriod.xml
structuredefinitions/UKCore-OrganizationAffiliation.xml
valuesets/ValueSet-UKCore-DateTimeType.xml

Draft OrgAffiliation

---

structuredefinitions/UKCore-Observation-InspiredOxygen.xml

Sprint7/ObsInspiredOxygen Changes

---

valuesets/ValueSet-UKCore-BodyPosition.xml

Updated BodyPosition valueset to match US vital signs one which includes Tredelenburg's... source: https://build.fhir.org/ig/HL7/cimi-vital-signs/ValueSet-bodyPositionVS.html

IOPS-2246 - Updated concept list to match US Vital Signs

---

examples/UKCore-Extension-Note-Example.xml

IOPS-2138 STU3 Fix diagnostic report extension note example

---

codesystems/CodeSystem-UKCore-MedicationRequestCategory.xml

Having True on the inactive causes a rendering issue on simplifier

alter True to true to fix Simplifier render issue

---

structuredefinitions/Extension-UKCore-CuffSize.xml
structuredefinitions/Extension-UKCore-SampleCategory.xml

Bidning was on value[x].coding, rather than value[x]

Fix incorrectly positioned binding on value[x].coding

---

valuesets/ValueSet-UKCore-MedicationRequestCategory.xml

this was causing 2 issues - an "unexpected token u in json" in the validator, and simplifier to not render these 2 resources

Fix True to true in medreq category (stu3)

---

.github/workflows/terminology.yml
codesystems/CodeSystem-NHSDataModelAndDictionary-DischargeDestination.xml
codesystems/CodeSystem-UKCore-AdmissionMethodWales.xml
codesystems/CodeSystem-UKCore-DischargeMethodEngland.xml
codesystems/CodeSystem-UKCore-DischargeMethodWales.xml
codesystems/CodeSystem-UKCore-OutcomeOfAttendanceEngland.xml
codesystems/CodeSystem-UKCore-OutcomeOfAttendanceWales.xml
conceptmaps/ConceptMap-UKCore-AdministrativeGender.xml
conceptmaps/ConceptMap-UKCore-MaritalStatus.xml
examples/UKCore-Appointment-OrthopaedicSurgery-Example.xml
examples/UKCore-Extension-CodingSCT-IllicitDrugs-Example.xml
examples/UKCore-Extension-CodingSCT-Weight-Example.xml
examples/UKCore-Extension-CollectionCollector-Example.xml
examples/UKCore-Extension-MedicationChangeSummary-Example.xml
examples/UKCore-HealthcareService-OrthopaedicService-Example.xml
examples/UKCore-Observation-Lab-Sn-AbsentData-Example.xml
examples/UKCore-RequestGroup-Ciprofloxacin-Example.xml
examples/UKCore-RequestGroup-MultipleAnitibiotics-Example.xml
examples/UKCore-RequestGroup-Paracetamol-Example.xml
examples/UKCore-Schedule-Immunization-Example.xml
examples/UKCore-Slot-AvailableWalkInVisit-Example.xml
structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
valuesets/ValueSet-UKCore-RespirationRate.xml

Majority of issues that were being hidden by warnings being ignored in UK Core fixed

Fix silent warnings

---

codesystems/CodeSystem-UKCore-ConditionCategory.xml
valuesets/ValueSet-UKCore-ConditionCategory.xml

Updated ValueSet but didnt think it needed a version/date change just for the expansion

STU2 - remove issue from CodeSystem

---

structuredefinitions/Extension-UKCore-DiagnosticReportNote.xml
structuredefinitions/UKCore-DiagnosticReport-Lab.xml
structuredefinitions/UKCore-DiagnosticReport.xml

set dr note cardinality to 0..* (STU2)

---

structuredefinitions/Extension-UKCore-MainLocation.xml

Alter mainLocation extension max cardinality

---

examples/UKCore-Patient-Sn-Makaton-Example.xml
examples/UKCore-Patient-Sn-MultipleLanguages-Example.xml
examples/UKCore-Patient-Sn-SingleLanguage-Example.xml
structuredefinitions/UKCore-RelatedPerson.xml

IG renders them out of the main branch, but copy of the snippets for the package, and the fix for relatedperson binding

human language snippets (STU2)

---

examples/UKCore-Patient-Sn-Makaton-Example.xml
examples/UKCore-Patient-Sn-MultipleLanguages-Example.xml
examples/UKCore-Patient-Sn-SingleLanguage-Example.xml
structuredefinitions/UKCore-RelatedPerson.xml

3 snippets - single language, multiple languiages, with proficiencies, and makaton as 2 codings

Patient language snippets (stu3)

---

examples/UKCore-DiagnosticReport-CTChestScan-Example.xml
examples/UKCore-DiagnosticReport-ECG-Example.xml
examples/UKCore-ServiceRequest-CTChestScan-Example.xml
examples/UKCore-ServiceRequest-ECG-Example.xml

2 additional DiagnosticReport examples from wales, uk-core'ifed

Wales examples

---

.github/workflows/terminology.yml

as superceeded by options.json

removed failonwarning from action

---

structuredefinitions/Extension-UKCore-BirthSex.xml
structuredefinitions/Extension-UKCore-ConditionEpisode.xml
structuredefinitions/Extension-UKCore-DeliveryChannel.xml
structuredefinitions/Extension-UKCore-ListWarningCode.xml
structuredefinitions/Extension-UKCore-RecordingSetting.xml

Valuesets accidently removed when changing from coding to codeableConcept. These have been readded

readded missing valuesets

---

examples/UKCore-Immunization-InfluenzaVaccine-Example.xml

Fix missing Location/

---

examples/UKCore-DiagnosticReport-DiagnosticStudiesReport-Example.xml
examples/UKCore-DiagnosticReport-Lab-DiagnosticStudiesReport-Example.xml
examples/UKCore-QuestionnaireResponse-BabyPatientSurvey-Example.xml
examples/UKCore-RequestGroup-MultipleAnitibiotics-Example.xml

Profile type missing from reference value. This is needed to create url link to said instance.
Readded UKCore-DiagnosticReport-DiagnosticStudiesReport-Example as it was accidentally removed from STU3

Update incorrect reference values

---

examples/UKCore-Practitioner-ConsultantSandraGose-Example.xml
examples/UKCore-Practitioner-DoctorPaulRastall-Example.xml
examples/UKCore-Practitioner-PharmacistJimmyChuck-Example.xml

Fixes relates to https://simplifier.net/hl7fhirukcorer4/ukcore-practitioner-doctorpaulrastall-example/~issues/3316
Where wrong system used, changes to system only.
For Jimmy Check kept SDS identifier and added gphc number. Number was randomly generated and checked to ensure it is not being used currently https://www.pharmacyregulation.org/registers

added correct system values

---

.github/python_scripts/check_assets_in_IG.py
.github/python_scripts/create_pages.py

A few issues with the creation of pages which this PR Fixes

Check IG Script working
