NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN

codesystems/CodeSystem-UKCore-NHSNumberVerificationStatus.xml, codesystems/CodeSystem-UKCore-NHSNumberVerificationStatusEngland.xml, codesystems/CodeSystem-UKCore-NHSNumberVerificationStatusWales.xml, valuesets/ValueSet-UKCore-NHSNumberVerificationStatus.xml
Split the codesystem into separate England and Wales files and changed the valueset to reflect this. Old codesystem with them both combined needs removing. 
Can we just delete it off git or do we need to keep it and set it to retired in Simplifier?
=> Fix/ballot 1.0.0 issue 188

examples/UKCore-AllergyIntolerance-EnteredInError-Example.xml, examples/UKCore-AllergyIntolerance-Extension-AllergyIntolEnd-Example.xml, structuredefinitions/Extension-UKCore-AllergyIntoleranceEnd.xml, structuredefinitions/UKCore-AllergyIntolerance.xml
Regarding the AllergyIntolerance profile: As the extension UKCore-AllergyIntoleranceEnd is to present additional information about clinicalStatus, the extension now points to the clinicalStatus element itself (rather than as a standalone extension).
Changes carried out in Forge.
@SheenaSharma
=> Fix/ballot 1.0.0 issue 103

examples/UKCore-MedicationRequest-Extension-RepeatInformation-Example.xml, structuredefinitions/Extension-UKCore-MedicationRepeatInformation.xml
Problem: MedicationRequest contains the numberOfRepeatsAllowed field and the validityPeriod field. Reccomended that these fields are used instead of the extension, or clarification is required on what information this extension captures that is not applicable to those two fields.
I've decided the best approach is to remove the authorisationExpiryDate from the extension as this is a duplicate of the validityPeriod within the profile. numberOfPrescriptionsIssued is different to the numberOfRepeatsAllowed so is staying. One example updated to reflect new change. IG to be updated to explain this better.
Do we need to change the extension name to be mre descriptive, e.g MedicationRepeatInformation to MedicationNumberRepeatsIssued ?
=> Fix/ballot 1.0.0 issue 64

examples/UKCore-Patient-BabyPatient-Example.xml, examples/UKCore-Patient-RichardSmith-Example.xml
Most examples were updated to replace <line value="LEEDS"> with <city value="LEEDS">, but 2 examples still had the old format, this updates them
=> Fixed address examples where city was still line

structuredefinitions/UKCore-PractitionerRole.xml, valuesets/ValueSet-UKCore-PractitionerRoleCode.xml
removed PractitionerRole.code and retired the UKCore PractitionerRoleCode valueset, as it was the same as the base fhir spec valueset
=> remove/retire UKCore PractitionerRoleCode

examples/UKCore-Condition-Extension-CodingSCTDescId-Example.xml, structuredefinitions/Extension-UKCore-CodingSCTDescDisplay.xml
Changed UKCore extension to be a child of coding as you cannot extend another extension that has value[x]. Fixed example to suit.
=> changed UK extension to coding, fixed example

examples/UKCore-PractitionerRole-Sn-Organization-Code-Example.xml
Changed to sds-role-profile-id to use 
value="100334993514" instead of the UUID.
=> Changed <identifier>

structuredefinitions/UKCore-Immunization.xml, structuredefinitions/UKCore-Medication.xml, structuredefinitions/UKCore-MedicationAdministration.xml, structuredefinitions/UKCore-MedicationDispense.xml, structuredefinitions/UKCore-MedicationRequest.xml, structuredefinitions/UKCore-MedicationStatement.xml
Change UKCore-MedicationCode binding strength from extensible to preferred on all 5 profiles that its bound to (with date and version uplift), as per DA discussion
=> Fix uk core medication code binding strength

codesystems/CodeSystem-UKCore-MessageEvent.xml, structuredefinitions/UKCore-MessageHeader.xml, valuesets/ValueSet-UKCore-MessageEvent.xml
Updated UKCore_MessageHeader.event[x] binding strength from extensible to prefered, and swapped valueset to use the 2 existing NHSD codesystems, rather than the blank UKCore one. and retired blank ukcore one
=> Fix uk core MessageHeader.event. binding strength and codesystems

structuredefinitions/UKCore-MessageHeader.xml
as per standup call discussion, set binding to MessageEvent valueset which uses NHSD codesystems to 'example'
=> set messageevent binding to example

codesystems/CodeSystem-UKCore-PersonMaritalStatusEngland.xml, valuesets/ValueSet-UKCore-PersonMaritalStatusCode.xml
https://nhsd-jira.digital.nhs.uk/browse/IOPS-950
As requested by NA, I have filtered the PersonMaritalStatus valueset with the requested codes.
I have also removed the total/offset in the expansion as per DK suggestion
CodeSystem required a change because it was missing 8 | Not applicable, because we'd used the attribute list not data element list
=> Fixes for 1.0.0/martial status filtering

examples/UKCore-AllergyIntolerance-Amoxicillin-Example.xml, examples/UKCore-AllergyIntolerance-Extension-Evidence-Example.xml, examples/UKCore-AllergyIntolerance-Sn-DrugAllergy-Example.xml, examples/UKCore-AllergyIntolerance-Sn-DrugAllergyToEggProtein-Example.xml, examples/UKCore-AllergyIntolerance-Sn-NegHandlNoKnownAllergies-Example.xml, examples/UKCore-AllergyIntolerance-Sn-NonDrugAllergy-Example.xml, examples/UKCore-VitalSigns-Observation-OxygenSaturation-Example.xml
Fix stu2 patient references
from "Patient/UKCore-RichardSmith-Patient-Example"
to "Patient/UKCore-Patient-RichardSmith-Example"
=> fix stu2 examples with incorrect patient references

codesystems/CodeSystem-UKCore-NHSNumberVerificationStatusEngland.xml
As per jira ticket, Data Model Dictionary related codesystems were checked for differences, NHSNumberVerificationStatusEngland was found not to have a source of data or expansion date listed
=> Added source and date of latest expansion

structuredefinitions/UKCore-PractitionerRole.xml
as discussed and agreed, PractitionerRole.healthcareService was pointing at HealthcareService, but we have a UKCore-HealthcareService
=> Update PractitionerRole reference to ukcore-healthcareservice

valuesets/ValueSet-UKCore-ConditionEpisodicity.xml, valuesets/ValueSet-UKCore-ListWarningCode.xml
Checks on 1.0.0 highlighted 2 valusets with ukcore codesystems, where the expansion contained references to fhir.nhs.uk
Both valusets updated with fresh expansions
=> Fixed system url for ukcore codesystem pointing at nhs.uk

structuredefinitions/UKCore-Consent.xml
On producing IG page, noticed the description didn't list / format correctly, and there were missing references to uk core profiles
=> Updated version, status, date, description and references to uk core profiles

structuredefinitions/UKCore-Consent.xml, structuredefinitions/UKCore-DiagnosticReport.xml
I jumped the gun on setting the CTA6 profiles I'd updated to active, resetting them to draft
No date/version change needed as already uplifted for cta6
=> Rest cta6 profiles to draft

valuesets/ValueSet-UKCore-ACVPU.xml
LOW PRIORITY
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1074
Issue raised on simplifier - valueset is draft, unused, and could probably be retired as its contents exist in another, but the filter IS wrong
Updated description to be inline with valueset design approach, but testing a new way of displaying the filter (list of: - concept | term)
Removed |term| on the include filter concepts, as per guidance (systems may not be able to understand the pipe)
Added expansion of the filter
Pretty print
=> Snomed CT filter is missing OR

valuesets/ValueSet-UKCore-PracticeSettingCode.xml
UKCore-PracticeSettingCode valueset was not expanded during 1.0.0 work, possibly due to time constraint, but more likely due to a swagger constraint (new codesystem)
Expanded for STU2 onwards - haven't changed the date/version as no change in the valuesets actual definition/description
=> Expansion of codesystem into PracticeSettingCode valueset

structuredefinitions/Extension-UKCore-ActualProblem.xml, structuredefinitions/Extension-UKCore-AssociatedEncounter.xml, structuredefinitions/Extension-UKCore-BookingOrganization.xml, structuredefinitions/Extension-UKCore-DeliveryChannel.xml, structuredefinitions/Extension-UKCore-EncounterTransport.xml, structuredefinitions/Extension-UKCore-LegalStatus.xml, structuredefinitions/Extension-UKCore-ProblemSignificance.xml, structuredefinitions/Extension-UKCore-Recorder.xml, structuredefinitions/Extension-UKCore-RelatedClinicalContent.xml, structuredefinitions/Extension-UKCore-RelatedProblemHeader.xml
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1134 and https://nhsd-jira.digital.nhs.uk/browse/IOPS-1135
Coming out of Ryans DesignApproach meeting, we had a few extensions without min value =1 on value[x]
In fixing those, I noticed a couple of extensions had not got identifer.assigner referencing ukcore-org
And duff url for an extension (draft, url doesn't match name)
=> Fix min value on value[x], and missing assigner references

valuesets/ValueSet-UKCore-SpecimenBodySite.xml, valuesets/ValueSet-UKCore-SpecimenType.xml
Minor tweaks to description and filtering on the 2 Specimen related valuesets for sprint 6, in line with design approach ig.
Updated date and version to be in line with other pre sprint 6 changes
=> Fix for specimen SNOMED valuesets to bring in line with design approach

structuredefinitions/UKCore-Observation-VitalSigns.xml, structuredefinitions/UKCore-VitalSigns-Observation.xml
Removed unneccessary referencing in the derived ukcore-observation-vitalsigns (and the retired ukcore-vitalsigns-observation), updated hasMember/basedOn with correct ukcore profiles in line with ukcore-observation
=> Fix obs vital signs references

structuredefinitions/UKCore-Specimen.xml
>The draft UKCore-Specimen profile, has an open slice on element Specimen.collection.bodySite, snomedCT, bound to >[ValueSet UKCore-SpecimenBodySite](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence>/Home/Terminology/AllValueSets/ValueSet-UKCore-SpecimenBodySite?version=1.6.0) (preferred).
>
>The origins of this slice are from the FHIR STU3 CareConnect Specimen profile, and the now retired Extension-UKCore-CodingSCTDescId.
>
>    Remove the slice
>    Bind Specimen.collection.bodySite to [ValueSet UKCore-SpecimenBodySite](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-SpecimenBodySite?version=1.6.0) (preferred)
=> removed collection.bodySite slice. Moved ValueSet

structuredefinitions/UKCore-DiagnosticReport.xml
>The draft UKCore-DiagnosticReport profile, has an open slice on element DiagnosticReport.conclusionCode, snomedCT, bound to [ValueSet UKCore-FindingCode](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-FindingCode?version=1.6.0) (preferred).
>
>The origins of this slice are from the FHIR STU3 CareConnect Specimen profile, and the now retired Extension-UKCore-CodingSCTDescId.
>
>Remove the slice
>Bind DiagnosticReport.conclusionCode to [ValueSet UKCore-FindingCode](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-FindingCode?version=1.6.0) (preferred)
=> removed slice, changed binding

structuredefinitions/UKCore-DiagnosticReport.xml
>The draft UKCore-DiagnosticReport profile, has an open slice on element DiagnosticReport.code, snomedCT, bound to [ValueSet UKCore-ReportCodeSnCT](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-ReportCodeSnCT?version=1.6.0) (preferred).
>
>The origins of this slice are from the FHIR STU3 CareConnect Specimen profile, and the now retired Extension-UKCore-CodingSCTDescId.
Note the ValueSet UKCore-ReportCodeSnCT has now been renamed to UKCore-ReportCode
=> removed slice to code, added new binding

structuredefinitions/Extension-UKCore-BodySiteReference.xml, structuredefinitions/UKCore-Specimen.xml
>The FHIR R5 snapshot of the [Specimen](https://hl7.org/fhir/5.0.0-snapshot3/Specimen.html) resource, has a change to >Specimen.collection.bodySite, altering the data type of the element from CodeableConcept to CodeableReference >(BodyStructure).
>Genomics have a use case for referencing the BodyStructure. 	
>Backport the R5 functionality as a new extension: Extension-UKCore-BodySiteReference
=> added backport ref

structuredefinitions/UKCore-DiagnosticReport.xml
>The draft UKCore-DiagnosticReport profile, has an open slice on element DiagnosticReport.category, snomedCT, with no ValueSet bound.
>
>The origins of this slice are from the FHIR STU3 CareConnect Specimen profile, and the now retired Extension-UKCore-CodingSCTDescId.
=> removed slice from category.coding

structuredefinitions/UKCore-Observation.xml
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1303
https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Proposed-Changes/Issue-12?version=1.6.0
The draft UKCore-Observation profile, has an open slice on element Observation.bodySite, snomedCT, bound to [ValueSet UKCore-BodySite](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-BodySite?version=1.6.0) (preferred).
The origins of this slice are from the FHIR STU3 CareConnect Specimen profile, and the now retired Extension-UKCore-CodingSCTDescId.
Remove slice
Bind Observation.bodySite to [ValueSet UKCore-BodySite](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-BodySite?version=1.6.0) …
=> Removed Observation bodySite Slice

structuredefinitions/Extension-UKCore-PriorityReason.xml, structuredefinitions/UKCore-ServiceRequest.xml
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1316
https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Proposed-Changes/Issue-27?version=1.6.0
There is a Genomics use case to record the reason why an urgent test has been requested. This differs from supportingInfo in that it does not necessarily indicate why the test is being requested. No other fields in ServiceRequest were appropriate.
Add a new extension: Extension-UKCore-PriorityReason, with a binding to [ValueSet UKCore-ServiceRequestReasonCode](https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-ServiceRequestReasonCode?version=1.6.0)
=> Sprint 6 service req priority reason extension

codesystems/CodeSystem-UKCore-FundingCategory.xml, examples/UKCore-ServiceRequest-Extension-Coverage-Example.xml, structuredefinitions/Extension-UKCore-Coverage.xml, structuredefinitions/UKCore-ServiceRequest.xml, valuesets/ValueSet-UKCore-FundingCategory.xml
https://nhsd-jira.digital.nhs.uk/browse/IOPS-1317
https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Proposed-Changes/Issue-28?version=1.6.0
There is a Genomics use case to record the funding category for a ServiceRequest. It is expected this would be populated with a code indicating whether the service request is part of NHS coverage or private, and would be used for reimbursement purposes by receiving labs.
Add a new extension: Extension-UKCore-Coverage
=> Sprint 6 service request - coverage extension

examples/UKCore-Condition-Sn-Extension-Translation-Example.xml
Snippet of using the core defined translation extension, will be added to either codeableconcept guidance section, or a separate page,  to be used to resolve the hackathon raised issue
=> Snippet example for translation extension

structuredefinitions/UKCore-DiagnosticReport-Lab.xml, structuredefinitions/UKCore-Observation-Lab.xml, structuredefinitions/UKCore-Observation-LabGroup.xml
- change result cardinality back to base
- add derived profiles to result
- change effective constraint to warning
- create slice on category
- change code to fixed value
- rename to include Lab in title
- slice category as above
- value[x] add constraint to warn not to use
- change value back to base
- slice on category for Obs-Lab (I did not explicitly write this down as an action but presume it wanted doing?)
- warning constraint on value[x] / dataAbsenseReason / Note to say 1 of 3 SHALL exist
TODO
- Check UTL codes have changed  
- change examples to ensure constraints work
=> added changes as discussed

examples/UKCore-ServiceRequest-Extension-PriorityReason_SendingAsText-Example.xml
Add PriorityReason Example for sending text - no need to add anything to extension, ans codeableconcept allows us to use the .text
=> Add PriorityReason Example for sending text

examples/UKCore-DiagnosticReport-Extension-DeviceReference-Example.xml, examples/UKCore-Specimen-Extension-SampleState-Example.xml
updated DeviceReference and SampleState example filenames to matcht he standard, but forgot to update the ID's, hence this pr
=> Set ID on extension examples to match updated filenames

structuredefinitions/UKCore-FamilyMemberHistory.xml
As per call, use UKCOre PersonaRelationshipType as the valueset, with additional IG guidance
=> Rebind FMH relationship to UKCore Valuset

examples/UKCore-MedicationDispense-ParacetamolOral-Example.xml, examples/UKCore-RequestGroup-Paracetamol-Example.xml
Lack of resource/ on the med dispense meant simplifier couldn't render it
and request group had the right resource/ but not the right resource within that
=> Fix missing / slightly broken references on RequestGroup example

structuredefinitions/UKCore-Observation-Lab.xml, structuredefinitions/UKCore-Observation-LabGroup.xml, structuredefinitions/UKCore-ServiceRequest-Lab.xml, valuesets/ValueSet-UKCore-PathologyAndLaboratoryMedicineObservables.xml, valuesets/ValueSet-UKCore-PathologyAndLaboratoryMedicineProcedures.xml, valuesets/ValueSet-UKCore-UnifiedTestList.xml
UTL changed from single now inactive refset to two palm ones for observables and procedures. Observables valueset also needs the old pbcl refset, which is currently inactive (should be reactivated in end of nov snomed ct release)
2 new valuesets, and rebinding with version / date upgrade for 3 profiles that used utl
Will need to go into STU2, and IG changes in stu2/3
=> stu3 iops2144 utl change

examples/UKCore-Extension-BirthSex-Example.xml, examples/UKCore-Medication-Extension-MedicationTradeFamily-Example.xml, examples/UKCore-Patient-Extension-BirthSex-Example.xml, structuredefinitions/Extension-UKCore-BirthSex.xml, structuredefinitions/Extension-UKCore-ConditionEpisode.xml, structuredefinitions/Extension-UKCore-DeliveryChannel.xml, structuredefinitions/Extension-UKCore-ListWarningCode.xml
- Fix the missing valueset bindings in STU2 as per https://github.com/NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN/pull/552 . Note: structuredefinitions/Extension-UKCore-RecordingSetting.xml is not in this branch
- BirthSex example fixed and brought in line with STU3
The title values will not change in this version, so ignore QC Checker
=> readd missing valuesets to STU2

examples/UKCore-Composition-Discharge-Example.xml, examples/UKCore-Extension-ConditionEpisode-Example.xml, examples/UKCore-Extension-DeviceReference-Example.xml, examples/UKCore-Extension-PriorityReason-Example.xml, examples/UKCore-Extension-PriorityReason-SendingAsText-Example.xml, examples/UKCore-Extension-TriggeredBy-Example.xml, examples/UKCore-Observation-24HourBloodPressure-Example.xml, examples/UKCore-Observation-BreathingNormally-Example.xml, examples/UKCore-Observation-DrugUse-Example.xml, examples/UKCore-Observation-FastingTest-Example.xml, examples/UKCore-Observation-FingerJointInflamed-Example.xml, examples/UKCore-Observation-Group-FullBloodCount-Example.xml, examples/UKCore-Observation-HeavyDrinker-Example.xml, examples/UKCore-Observation-Lab-RedCellCount-Example.xml, examples/UKCore-Observation-Lab-WhiteCellCount-Example.xml, examples/UKCore-Observation-OxygenTherapy-Example.xml, examples/UKCore-Observation-PatientConsciousness-Example.xml, examples/UKCore-Observation-PipeSmoker-Example.xml, examples/UKCore-Observation-VitalSigns-HeartRate-Example.xml, structuredefinitions/UKCore-DiagnosticReport-Lab.xml, structuredefinitions/UKCore-Observation-Group-Lab.xml, structuredefinitions/UKCore-Observation-Lab.xml, structuredefinitions/UKCore-Observation-VitalSigns.xml, structuredefinitions/UKCore-Organization.xml, structuredefinitions/UKCore-Patient.xml, structuredefinitions/UKCore-ServiceRequest.xml, valuesets/ValueSet-UKCore-MedicationRequestCategory.xml
All Assets and examples checked for JSON rendering errors. This is due to new updates in Simplifier which will show an error in the JSON render if the XML has elements out of order. The XML render is actually reordered correctly so can just be copied from there rather than having to work out the order manually.
Note: The Simplifier QC Checker does not pick these up. This will be fixed later this year, but I have added a check in our own QC Checker to pick these up.
All assets have had their version patch number updated and date updated
=> reordered elements to follow FHIR standards

examples/UKCore-Extension-TriggeredBy-Example.xml, examples/UKCore-Observation-DrugUse-Example.xml, examples/UKCore-Observation-Group-FullBloodCount-Example.xml, examples/UKCore-Observation-HeavyDrinker-Example.xml, examples/UKCore-Observation-Lab-RedCellCount-Example.xml, examples/UKCore-Observation-Lab-Sn-AbsentData-Example.xml, examples/UKCore-Observation-Lab-WhiteCellCount-Example.xml, examples/UKCore-Observation-OxygenTherapy-Example.xml, examples/UKCore-Observation-PipeSmoker-Example.xml
Namespaces are missing in these examples, stopping the rendering of json within simplifier.
plus one fix on example text being incorrect
=> Fix missing namespaces

codesystems/CodeSystem-UKCore-PrimarySampleState.xml
Remove Frozen state from UKCore as it already exist in another HL7 CodeSystem http://terminology.hl7.org/CodeSystem/v2-0493, within the same ValueSet.
=> Remove Duplicate Option

structuredefinitions/Extension-UKCore-DiagnosticReportMedia.xml, structuredefinitions/Extension-UKCore-DiagnosticReportMediaLink.xml, structuredefinitions/UKCore-DiagnosticReport.xml
Changing the cardinality of Extension-DiagnosticReport.media.link to 0 to many (0...*) instead of the current 1 to many(1..*)
=> Cardinality Issues with Extension-DiagnosticReport.media.link

.simplifier/folder.settings.json, structuredefinitions/UKCore-Observation-VitalSigns-BodyHeight.xml, structuredefinitions/UKCore-Observation-VitalSigns.xml
As per https://simplifier.net/hl7fhirukcorer4/ukcore-observation-vitalsigns-bodyheight/~issues/3351
>After reviewing the use of units with clinical experts from different specialties in NHS Wales, it was deemed appropriate to use cm as the primary unit, especially in certain use cases where patients are very young (under 2 years old) and length is recorded instead of height. Length is always recorded as cm.
>
>Ideally, we should allow the use of both meters (m) and centimeters (cm) to accommodate this
Changed valueQuantity to valueCodeableConcept and reused an international valueset that includes all distances that contain (m) so this includes metres and centimetres. Reworded description so that it includes these two values and that body length for babies and infants are in scope.
Changes …
=> changed valueQuantity to valueCodeableConcept to allow for centimetres

valuesets/ValueSet-UKCore-BodySite.xml
From https://simplifier.net/hl7fhirukcorer4/~issues/3350
We have identified that binding against MedicationRequest.dosingInstructions.site could do with additional information. We would like the binding to include all descendants of the SNOMED hierarchy 278001007 | Nonspecific site |.
This would allow for the user case when a clinician is prescribing a cutanious cream or similar to an affected area of the skin. Rather than the clinician having to select all the areas of the body that are affected they can just select the code 22201000087104 | Affected area |.
=> add new sct descendant to ValueSet-UKCore-BodySite.xml

valuesets/ValueSet-UKCore-BloodPressure-Average.xml, valuesets/ValueSet-UKCore-BloodPressure.xml
This ticket has been created to fix the following:
https://simplifier.net/hl7fhirukcorer4/valueset-ukcore-bloodpressure-average/~issues/3352
https://simplifier.net/hl7fhirukcorer4/valueset-ukcore-bloodpressure/~issues/3353
For ValueSet-UKCore-BloodPressure-Average
- removed 170599006 | 24 hr blood pressure monitoring (regime/therapy) | due to wrong Semantic Tag
- removed - 314463006 | 24 hour blood pressure (observable entity) | as not an average
- added DescendantOrSelfOf 2324511000000105 | Average 24 hour blood pressure (observable entity) |
- fixed MINUS calculation
For ValueSet-UKCore-BloodPressure
- Removed
- 392570002 | Blood pressure finding (finding) |
- 392571003 | Finding of arterial pulse pressure (finding) |
- 301141002 | Finding of pulmonary arterial pressure (finding) |
- …
=> Fix Blood Pressure ValueSets
